
'use server';
import { z } from 'zod';
import fetch from 'node-fetch';
import { callGemini, getPrimaryModel } from "@/ai/model-config";

const GetWeatherInfoInputSchema = z.object({
  lat: z.number().describe('The latitude for the location.'),
  lon: z.number().describe('The longitude for the location.'),
});
export type GetWeatherInfoInput = z.infer<typeof GetWeatherInfoInputSchema>;

const DailyForecastSchema = z.object({
  date: z.string().describe("The date for the forecast, e.g., 'Monday'."),
  weatherCode: z.number().describe("The WMO weather code."),
  maxTemp: z.number().describe("The maximum temperature."),
  minTemp: z.number().describe("The minimum temperature."),
});

const GetWeatherInfoOutputSchema = z.object({
  location: z.object({
    name: z.string().describe("The name of the location, e.g., 'Bengaluru, Bangalore Urban'"),
  }),
  current: z.object({
    temperature: z.number(),
    weatherCode: z.number(),
    humidity: z.number(),
    windSpeed: z.number(),
    isDay: z.number(),
  }),
  daily: z.array(DailyForecastSchema).describe("A 5-day forecast."),
  summary: z.string().describe("A short, conversational summary of the overall weather, generated by the AI."),
  sunrise: z.string().describe("Today's sunrise time, e.g., '06:05'"),
  sunset: z.string().describe("Today's sunset time, e.g., '18:45'"),
});
export type GetWeatherInfoOutput = z.infer<typeof GetWeatherInfoOutputSchema>;
async function weatherTool({ lat, lon }: { lat: number, lon: number }) {
    const weatherUrl = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m,is_day&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset&timezone=auto`;
    const geocodeUrl = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lon}`;

    const [weatherResponse, geocodeResponse] = await Promise.all([
      fetch(weatherUrl),
      fetch(geocodeUrl, { headers: { 'User-Agent': 'AgriSence-App/1.0' } })
    ]);

    if (!weatherResponse.ok) {
      throw new Error(`Failed to fetch weather data. Status: ${weatherResponse.status}`);
    }
    if (!geocodeResponse.ok) {
      // Don't fail the whole thing, just proceed without a location name
      console.error(`Failed to fetch geocoding data. Status: ${geocodeResponse.status}`);
    }

    const weatherData = await weatherResponse.json() as any;
    const geocodeData = geocodeResponse.ok ? await geocodeResponse.json() as any : null;

    let locationName = "Your Location";
    if (geocodeData?.address) {
      const { village, town, city, county, state, state_district } = geocodeData.address;
      locationName = [village, town, city, county, state_district, state].filter(Boolean).slice(0, 2).join(', ');
      if (!locationName) locationName = "Your Location";
    }

    const dailyForecasts = weatherData.daily.time.slice(0, 5).map((time: string, index: number) => ({
      date: new Date(time).toLocaleDateString('en-US', { weekday: 'long' }),
      weatherCode: weatherData.daily.weather_code[index],
      maxTemp: Math.round(weatherData.daily.temperature_2m_max[index]),
      minTemp: Math.round(weatherData.daily.temperature_2m_min[index]),
    }));

    return {
      location: {
        name: locationName
      },
      current: {
        temperature: Math.round(weatherData.current.temperature_2m),
        weatherCode: weatherData.current.weather_code,
        humidity: weatherData.current.relative_humidity_2m,
        windSpeed: Math.round(weatherData.current.wind_speed_10m),
        isDay: weatherData.current.is_day,
      },
      daily: dailyForecasts,
      sunrise: new Date(weatherData.daily.sunrise[0]).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
      sunset: new Date(weatherData.daily.sunset[0]).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
    };
  }

export async function getWeatherInfo(input: GetWeatherInfoInput): Promise<GetWeatherInfoOutput> {
try {
  // 1. Call the tool to get structured weather data.
  const structuredData = await weatherTool(input);

  let summary = 'The weather forecast is available below.'; // Default summary
  try {
    // 2. Call the AI to generate a summary from the structured data.
    const promptText = `You are a helpful weather assistant. Given the following weather data in JSON format, provide a short, conversational summary of the overall weather. For example "Looks like a clear day, but expect some rain showers later in the week."

    Data:
    ${JSON.stringify(structuredData, null, 2)}`;
    
    const responseText = await callGemini(promptText, {
      preferredModel: getPrimaryModel(),
      responseSchema: z.object({ summary: GetWeatherInfoOutputSchema.shape.summary })
    });
    
    const output = JSON.parse(responseText);
    
    if (output?.summary) {
      summary = output.summary;
    }
  } catch (error) {
    console.error('Could not generate weather summary from AI:', error);
    // Do not throw; proceed with a default summary.
  }

  // 3. Combine the structured data and the AI's summary.
  return {
    ...structuredData,
    summary,
  };
} catch (error) {
  console.error("Error in weatherFlow:", error);
  throw new Error("The weather service is currently unavailable. Please try again in a few moments.");
}
}
